server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  thymeleaf:
    suffix: .html 
    prefix: /WEB-INF/views/ 
    cache: false 